### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zaid-maker** [Freddywhest/ToMarketBot#10]
Getting this error while starting the bot @Freddywhest 

![image](https://github.com/user-attachments/assets/9dc8ee91-8654-4889-8399-e081a89d53ab)

**Comment by SarcasticBalak** [comment]
are u banned?

**Comment by Zaid-maker** [comment]
> are u banned?

Nope I can access from telegram

**Comment by Zaid-maker** [comment]
> > are u banned?
> 
> Nope I can access from telegram

![Screenshot_20241020-165738_Telegram](https://github.com/user-attachments/assets/da9d32de-1b7d-4ded-a470-77e7560ea915)
